name = "Grandis - Static Blog Generator"
title = "Grandis"
description = "Grandis is a customizable static site generator for blogs."
prefix = ""

[social]
twitter = ""

[style]
theme = "default"
layout = "default"
dark = true
