import { Route } from "../../src/route";
import Layout from "./components/default.layout";

const route = new Route("", {}).page(() => {
	return (
		<Layout>
			<h1>Grandis blog generator</h1>
			<p>This page is generated by grandis</p>
		</Layout>
	);
});

export default route;
